#!/bin/bash
if [ -z "$1" ] ; then
    echo "usage: $0 <mainfile> [clean|print|draft]"
    echo "draft mode is default"
    exit 1
fi
# strip off .tex if it's give
name=$(basename $1 .tex)

if [ "$2" = "clean" ] ; then
    rm -f $name.{blg,bbl,gls,glg,alg,acr,ist,aux,toc,tdo,out,lot,lof,glo,acn,log}
    if [ -f "${name}.pdf" ] ; then
        echo "Not removing:"
        echo "${name}.pdf"
    fi
    exit 0
fi

pdflatex="pdflatex $name"
if [ "$2" == "print" ] ; then
    pdflatex="pdflatex \def\isfinal{1} \input{$name}"
fi


$pdflatex || exit 1
$pdflatex || exit 1
bibtex $name || exit 1
$pdflatex || exit 1
$pdflatex || exit 1
makeindex -s $name.ist -t $name.glg -o $name.gls $name.glo || exit 1
makeindex -s $name.ist -t $name.alg -o $name.acr $name.acn || exit 1
# makeindex $name.nlo -s nomencl.ist -o $name.nls
$pdflatex || exit 1
$pdflatex || exit 1

